name = "DecemberFun"
uuid = "d34dd864-1770-4945-989e-0903143259f6"
authors = ["John Unwin <john@fingertip.co.nz> and contributors"]
version = "1.0.0-DEV"

[deps]

[compat]
Aqua = "0.8"
Test = "1"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
